### ISSUE TITLE
What is the purpose of output cartesian position column?

### ISSUE THREAD

**Issue by seshnadathur** [cosmodesi/pyrecon#3]
In the standalone `pyrecon` code, a ConfigError is raised if the output cartesian position column name is not specified in the config file when the input format is `xyz` (https://github.com/cosmodesi/pyrecon/blob/main/bin/pyrecon#L285` and https://github.com/cosmodesi/pyrecon/blob/main/bin/pyrecon#L340). But this column name does not appear to be used anywhere. I provided some random name just in order to avoid the error, and the output file produced does not contain it.

So perhaps these checks could be deleted?

**Comment by adematti** [comment]
You are 100% right, thanks! (probably a remnant of ancient versions...) This should be solved by commit 52417276b1a37004696ee52282542751930643f1.

**Comment by adematti** [comment]
Can we close the issue?

**Comment by seshnadathur** [comment]
Yup, this is all good.
